#!/bin/sh
#PBS -l procs=1,pmem=4gb
#PBS -l walltime=110:00:00
#PBS -j oe
#PBS -m a
#PBS -V
#PBS -M begumtop@umich.edu
#PBS -A pschloss_fluxod
#PBS -q fluxod
#PBS -l qos=flux

# Load Modules:
#  1) R/3.5.0   2) r-biomed-libs/3.5.0


cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR


make results/figures/Figure_1.pdf

echo "Script complete"
echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
qstat -f $PBS_JOBID
exit
